### ISSUE TITLE
form栏位的高度和table行高度的调整

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#1]
form栏位的高度和table行高度的调整

**Comment by guoxunbo** [comment]
![image](https://user-images.githubusercontent.com/14329149/48311019-aee67880-e5d3-11e8-9d2e-3b57d9545802.png)

**Comment by 18667931421** [comment]
已修复

**Comment by 18667931421** [comment]
![image](https://user-images.githubusercontent.com/42213513/48322229-78573f00-e661-11e8-8430-4ce42e1ad832.png)
