### ISSUE TITLE
EntityTable的新增按钮问题

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#12]
按钮不止新增一个。基本的默认的页面都必须具备导入，导出，新增的按钮。故不能放在右上角。应该在Table上面加个tableGroup。如图，画红线的地方。
![image](https://user-images.githubusercontent.com/14329149/48314064-12d26680-e5ff-11e8-8aea-9ab6c6176b8c.png)

**Comment by 18667931421** [comment]
![image](https://user-images.githubusercontent.com/42213513/48346722-fe51a500-e6b6-11e8-8777-13f57aa866f6.png)
