### ISSUE TITLE
COM晶圆发料

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#179]
只匹配界面显示的所有单据。不需要选单据，自动更新
中间表数据：根据型号/等级/二级代码/物流属性去更新(多
条匹配时，根据中间表SEQ从小到大去更新；涉及一次发料
要更新多个单据时，先把SEQ小的单据填满)。原数量
IQUANTITY，剩余数量LEFT_NUM，已发料数量
DELIVERED_NUM
（匹配不到型号、二级代码、等级、物流属性一致的单据，
系统提示：没有符合条件的单据，不做发料动作；
单据存在，数量不足，提示单据数量不足，不做发料动作；
单据存在，数量满足发料，发料成功，更新中间表数据。）

**Comment by guozhangluo** [comment]
给MES中backend_wafer_receive_his记录历史
![image](https://user-images.githubusercontent.com/55224413/77501428-fbfa8000-6e92-11ea-8cd8-f2e4c690c362.png)

**Comment by guozhangluo** [comment]
扫描箱号信息，验证箱中晶圆信息至少有一个晶圆绑定工单，如果没有绑定工单，不允许发料，给出错误提示
