### ISSUE TITLE
当列过少时，出现固定列会出现多个的问题

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#2]

**Comment by guoxunbo** [comment]
![image](https://user-images.githubusercontent.com/14329149/48311022-c45ba280-e5d3-11e8-9a0a-054c8d2f8114.png)

**Comment by 18667931421** [comment]
已修复 
![image](https://user-images.githubusercontent.com/42213513/48335540-06025100-e699-11e8-95e1-616133db3b3f.png)
