### ISSUE TITLE
快递接口相关修改

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#433]
1. 根据ERP过来的套账进行区分SH还是JS。给跨越传递不同的账号
2. 当选择是收方付的时候不传递号码。

**Comment by guoxunbo** [comment]
当选择是收方付的时候不传递customerCode

**Comment by guoxunbo** [comment]
当选择是收方付的时候不传递PaymentCustomer

**Comment by guozhangluo** [comment]
根据备货单号获取账套号
根据账套号区分SH和ZJ
