### ISSUE TITLE
MSCM接口

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#447]
1. 请求Token接口
![image](https://user-images.githubusercontent.com/14329149/103184969-49f65580-48f5-11eb-95c6-f75cb9145327.png)

2. 发货的时候记录快递单号接口
![image](https://user-images.githubusercontent.com/14329149/103184991-62ff0680-48f5-11eb-870b-4231eb0c7104.png)

**Comment by guozhangluo** [comment]
一个快递单号验证一次scm系统，没有快递单号快递公司和快递单号都传空字符串

**Comment by guozhangluo** [comment]
已经装箱的Lot也可以查询做标注

**Comment by guozhangluo** [comment]
对装箱的Lot需要验证Lot的标注信息是否一致，如果箱中的Lot都标注了  对箱也做标注；
取消标注:只要有一个Lot取消标注了，那么久取消箱号的标注信息。
