### ISSUE TITLE
SCM Hold/Release

### ISSUE THREAD

**Issue by guoxunbo** [guoxunbo/newbiest#640]
SCM Hold/Release 
- Hold: 当物料批次不存在时。则对其做预约Hold
- Release: SCM HOLD的只能是SCM 解除，SCM不能解除其他人的Hold

**Comment by guozhangluo** [comment]
Hold：批次信息不存在，预约设置已经存在，提示物料批次已经Hold；
Release：批次不存在，预约设置存在则删除预约设置，否则提示批次信息不存在；

**Comment by guozhangluo** [comment]
按照unitId查询Hold，不存在的做预约Hold处理
